name: CI CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/sohanlal33/devops-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/sohanlal33/devops-frontend:latest

      - name: Deploy using docker-compose
        run: |
          set -e
          cd /home/ubuntu/devops-assessment
          docker-compose pull
          docker-compose up -d
          sleep 10
          curl -f http://localhost || { echo "Frontend health check failed"; exit 1; }
          curl -f http://localhost:8000/api/hello/ || { echo "Backend health check failed"; exit 1; }

